accounts/urls.py
from django.urls import path




urlpatterns = [
  
]

blog/urls.py
from django.urls import path, include


urlpatterns = [
 
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog', include('blog.urls')),
    path('todo',include('todo.urls')),  
]

if settings.DEBUG:
 urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path, include
from todo import views


app_name = 'todo'

urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('create', views.task_create, name='task_create'),
    path("<int:task_id>/delete", views.task_delete, name='task_delete'),
    path("<int:task_id>/edit", views.task_edit, name='task_edit'),
    path("<int:task_id>/done", views.task_done, name='task_done'),

  
]

website/urls.py
from django.urls import path
from website  import views



app_name='website'

urlpatterns =[
    path('', views.index),
    path('about',views.about),
    path('contact',views.contact),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager,
    AbstractBaseUser,
    PermissionsMixin,
)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password and extra data.
        """
        if not email:
            raise ValueError(_("the Email must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_verified", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User Model for authentication management through email address instead of username
    """

    email = models.EmailField(max_length=255, unique=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    objects = UserManager()

    def __str__(self):
        return self.email

blog/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.
class TaskModel(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_done = models.BooleanField(default=False)

website/models.py
from django.db import models


# Create your models here.
class BasicInformationModel(models.Model):
    about = models.TextField()
    age = models.PositiveIntegerField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    language = models.CharField(max_length=255)
    
    
    def __str__(self):
        return f"BasicInfo {self.id}"
    
    class Meta:
        ordering = ['id']

class  SkillModel(models.Model):
    title = models.CharField(max_length=255)   
    level = models.PositiveBigIntegerField(default=50)  
    
    
    def __str__(self):
        return self.title    
    
    
class PhotoModel(models.Model):
    title = models.CharField(max_length=255,null=True)   
    image = models.ImageField(upload_to='photos/')
    
    
    # def __str__(self):
    #     return self.image  

todo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from todo.views import TaskModel


# class TaskForm(forms.Form):
#     title = forms.CharField()
#     description = forms.CharField(widget=forms.Textarea(),required=True)
    # def clean_description(self):
    #     description = self.cleaned_date.get('description')
    #     if any(char.isdigit() for char in description):
    #         raise ValidationError("description cannot contain numbers")
    #     return description

class TaskForm(forms.ModelForm):
    class Meta:
        model = TaskModel
        fields = ['title','description']

    def __init__(self, *args, **kwargs):
        super(TaskForm,self).__init__(*args,**kwargs)
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render

# Create your views here.

todo/views.py
from django.shortcuts import render, redirect, get_list_or_404
from todo.models import TaskModel
from todo.forms import TaskForm
from django.urls import reverse
from django.http import HttpResponseNotFound

def task_list(request):
    tasks = TaskModel.objects.all() 
    if search_q := request.GET.get("q"):
        #  task = task.filter(title=search_q )
        task = task.filter(title__icontains=search_q )
    return render(request,'todo/Task_list.html',context={'tasks':tasks})

def task_create(request):
    form = TaskForm()
    if request.method =="GET":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            # TaskModel.objects.create(title =form.changed_data['title'],
            #                           description=form.changed_data['description'])
            return redirect(reverse("todo:task_list"))
    return render(request,'todo/Task_create.html',context={'form':form})
    
    # if request.method =="POST":
    #     form = TaskForm()
    #     return render(request,'todo/Task_create.html',context={'form':form})



def task_delete(request, task_id):
    task = get_list_or_404(TaskModel,id=task_id)
    if task :
            task.delete()
    else:
            return HttpResponseNotFound()    
    return redirect(reverse("todo:task_list"))
    

def task_edit(request, task_id):
    task = get_list_or_404(TaskModel,task_id=id)
    form = TaskForm(instatnce=task)
    if request.method =="POST":
        form = TaskForm(data=request.POST,instance=task)
        if form.is_valid():
            form.save()
    return render(request,'todo/Task_edit.html',context={'form':form})




def task_done(request, task_id):
    task = get_list_or_404(TaskModel,id=task_id)
    if task :
            task.is_done = True
            task.save()
    return redirect(reverse("todo:task_list"))

website/views.py
from django.shortcuts import render
from django.http import HttpResponse
from website.models import BasicInformationModel, SkillModel, PhotoModel
    


def index(request):
    BasicInfo = BasicInformationModel.objects.first()
    Skills = SkillModel.objects.all()
    gallery = PhotoModel.objects.all()
    context ={
        'BasicInfo':BasicInfo,
        'Skills': Skills,
        'gallery':gallery,
        }
    return render(request, "website/index.html", context)

def about(request):
    return render(request, "website/about.html")

def contact(request):
    return render(request, "website/contact.html")
    
    

templates/components/footer.html
<footer class="py-3 my-4 fixed-bottom">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
    </ul>
  </footer>

templates/components/header.html
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
      </div>
    </div>
  </header>

templates/todo/Task_create.html
{% extends 'todo/base.html' %}
{% block content %} 
<main class="container mt-lg-5 pt-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Task Create</h5>
          <form  method="post" id ='task_create'>
            {{form.as_p}}
            {% csrf_token %}
          </form>

        </div>
        <div class="card-footer">
          < href="{% url "todo:task_create" %}"  type ="submit" class="btn btn-primary" form="task_create">Submit</a>
          <a  href="{% url "todo:task_list" %}" class="btn btn-secondary">Back</a>
        </div>
    </div>
</main>
{% endblock content %}

templates/todo/Task_list.html
{% extends 'todo/base.html' %}
{% block content %} 
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <form action="/search" method="GET" class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search..." aria-label="Search" name="q">
          <button class="btn btn-primary me-2" type="submit">Search</button>
          <a href="{% url "todo:task_create" %}" class="btn btn-success" >create</a>

        </form>
      </div>
    </div>
  </div>
<div class="container mt-5">
{% for task in tasks %}
<div class="row">
  <div class="col-lg-4 mb-4">
    <div class="card">
      <div class="card-body">
        <h5 class="{% if task.is_done %} text-decoration-line-through {% endif %}">{{task.title}}</h5>
        <div class="btn-group">
          <a href="{% url "todo:task_edit" task_id =task.id %}" class="btn btn-primary">Edit</button>
          <a href="{% url "todo:task_delete" task_id =task.id %}" class="btn btn-danger">Delete</button>
          {% if task.is_done %} 
          <a href="{% url "todo:task_done" %}" class="btn btn-success">Done</button>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
</div>
{% endblock content %}

templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head>
<body>
    {% include 'components/header.html' %}
    <main>
     
        {% block content %}
        

        {% endblock content %}
    </main>
    
    {% include 'components/footer.html' %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/todo/task_edit.html
{% extends 'todo/base.html' %}
{% block content %} 
<main class="container mt-lg-5 pt-5">

      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Task Edit</h5>
          <form  method="post" id ='task_edit'action="{% url "todo:task_edit" task_id=form.instance.id %}">
            {{form.as_p}}
            {% csrf_token %}
          </form>

        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary" form="task_edit">Submit</button>
          <a  href="{% url "todo:task_list" %}" class="btn btn-secondary">Back</a>
        </div>
    </div>
</main>
{% endblock content %}

templates/website/about.html
{% load static %}
<!DOCTYPE html>
<html lang ='en'>
    <head>
        <title>My Project</title>
        <link rel="stylesheet" href="{% static '/style.css' %}">
    </head>

    <body>
        <h1 class="red-title"  >about</h1>

    </body>
</html>

templates/website/contact.html
{% load static %}
<!DOCTYPE html>
<html lang ='en'>
    <head>
        <title>My Project</title>
        <link rel="stylesheet" href="{% static '/style.css' %}">
    </head>

    <body>
        <h1 class="red-title"  >contact</h1>

    </body>
</html>